### ISSUE TITLE
getAllData data structure

### ISSUE THREAD

**Issue by yidan** [RomainVialard/FirebaseApp#12]
Thanks for the great script! I used the library from the Google App Script and it works great! 
But one thing I noticed is when calling getAllData, the returned data is not in proper json format. Instead of having colons, it has equal signs. 

Here is an example return: 
[{-LINN2XT9wdCMEQGhZ9C={firstName=myname, yourSalary=200000, position=ioio, salary=100000}, -LINBdoUX4-s793E-cDW={firstName=abcdsad, position=hahahhahha, salary=1223434}, -LINDhN0TNmOcP6Y6_Qq={firstName=yourname, yourSalary=2000000, position=senior leader}}]

Any clue what went wrong?

**Comment by JeanRemiDelteil** [comment]
Hello @yidan ,

This output is only the Logger.log() output format, the real object is of correct JSON format.
Notice how the string are written without being surrounding quota ?
