### ISSUE TITLE
Outdated Firebase JS Library. Pls, Update the Tutorial

### ISSUE THREAD

**Issue by lekeope** [RomainVialard/FirebaseApp#21]
<script src="https://cdn.firebase.com/js/client/2.2.7/firebase.js"></script> is outdated

The latest one as of March 2019
<script src="https://www.gstatic.com/firebasejs/5.9.2/firebase-app.js"></script>

**Comment by krishnans** [comment]
Just curious, where did you found this code in the source file
<script src="https://cdn.firebase.com/js/client/2.2.7/firebase.js"></script>
I couldn't find it in src folder.

**Comment by JeanRemiDelteil** [comment]
@Edge-Developer This library is server side, and a such does not use the client SDK.

I'm closing the issue, as the tutorial is a different matter.
