### ISSUE TITLE
PushData without inserting unique subpath

### ISSUE THREAD

**Issue by jrob256** [RomainVialard/FirebaseApp#8]
Looking for a feature to be added. If the pushdata method could optionally push directly into the path.

Currently, if I use the pushdata method it will add a subpath with a unique id under the selected path. It would be great if that object information could be added directly under the specified path instead of creating a subPath with the unique id.

I could loop through to create a record every time but this will be very slow.

This could be useful if I need to add multiple spreadsheets to a single database but do not want to overwrite the information.

**Comment by JeanRemiDelteil** [comment]
Hello @jrob256 ,
The push command is designed to push new data with a unique key identifier:
Here is the related documentation for: [push](https://firebase.google.com/docs/reference/js/firebase.database.Reference#push)

You can achieve what you described using an update.
Here is the doc for: [update](https://firebase.google.com/docs/reference/js/firebase.database.Reference#update)

Read this documentation from Firebase, it provides a great example:
https://firebase.google.com/docs/database/web/read-and-write#update_specific_fields
